# api/config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm

  mappings:
    character_object:
      uri_prefix: /media/character
      upload_destination: '%kernel.project_dir%/public/media/character'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
